from PyQt5 import QtCore, QtGui, QtWidgets

k = 0
x1 = 0
y1 = 0
x2 = 0
y2 = 0
j = 0

class Ui_MainWindo(object):
    def setupUi(self, MainWindo):
        MainWindo.setObjectName("MainWindo")
        MainWindo.resize(728, 527)
        self.centralwidget = QtWidgets.QWidget(MainWindo)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton_14 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_14.setGeometry(QtCore.QRect(70, 60, 51, 51))
        self.pushButton_14.setMouseTracking(False)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("elitefon.ru-18481.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_14.setIcon(icon)
        self.pushButton_14.setIconSize(QtCore.QSize(500, 500))
        self.pushButton_14.setObjectName("11")
        self.pushButton_15 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_15.setGeometry(QtCore.QRect(120, 110, 51, 51))
        self.pushButton_15.setMouseTracking(False)
        self.pushButton_15.setIcon(icon)
        self.pushButton_15.setIconSize(QtCore.QSize(500, 500))
        self.pushButton_15.setObjectName("pushButton_15")
        self.pushButton_16 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_16.setGeometry(QtCore.QRect(170, 160, 51, 51))
        self.pushButton_16.setMouseTracking(False)
        self.pushButton_16.setIcon(icon)
        self.pushButton_16.setIconSize(QtCore.QSize(500, 500))
        self.pushButton_16.setObjectName("pushButton_16")
        self.pushButton_17 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_17.setGeometry(QtCore.QRect(220, 210, 51, 51))
        self.pushButton_17.setMouseTracking(False)
        self.pushButton_17.setIcon(icon)
        self.pushButton_17.setIconSize(QtCore.QSize(500, 500))
        self.pushButton_17.setObjectName("pushButton_17")
        self.pushButton_18 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_18.setGeometry(QtCore.QRect(270, 260, 51, 51))
        self.pushButton_18.setMouseTracking(False)
        self.pushButton_18.setIcon(icon)
        self.pushButton_18.setIconSize(QtCore.QSize(500, 500))
        self.pushButton_18.setObjectName("pushButton_18")
        self.pushButton_19 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_19.setGeometry(QtCore.QRect(320, 310, 51, 51))
        self.pushButton_19.setMouseTracking(False)
        self.pushButton_19.setIcon(icon)
        self.pushButton_19.setIconSize(QtCore.QSize(500, 500))
        self.pushButton_19.setObjectName("pushButton_19")
        self.pushButton_20 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_20.setGeometry(QtCore.QRect(370, 360, 51, 51))
        self.pushButton_20.setMouseTracking(False)
        self.pushButton_20.setIcon(icon)
        self.pushButton_20.setIconSize(QtCore.QSize(500, 500))
        self.pushButton_20.setObjectName("pushButton_20")
        self.pushButton_21 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_21.setGeometry(QtCore.QRect(420, 410, 51, 51))
        self.pushButton_21.setMouseTracking(False)
        self.pushButton_21.setIcon(icon)
        self.pushButton_21.setIconSize(QtCore.QSize(500, 500))
        self.pushButton_21.setObjectName("pushButton_21")
        self.pushButton_22 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_22.setGeometry(QtCore.QRect(170, 60, 51, 51))
        self.pushButton_22.setMouseTracking(False)
        self.pushButton_22.setIcon(icon)
        self.pushButton_22.setIconSize(QtCore.QSize(500, 500))
        self.pushButton_22.setObjectName("pushButton_22")
        self.pushButton_23 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_23.setGeometry(QtCore.QRect(420, 210, 51, 51))
        self.pushButton_23.setMouseTracking(False)
        self.pushButton_23.setIcon(icon)
        self.pushButton_23.setIconSize(QtCore.QSize(500, 500))
        self.pushButton_23.setObjectName("pushButton_23")
        self.pushButton_24 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_24.setGeometry(QtCore.QRect(220, 110, 51, 51))
        self.pushButton_24.setMouseTracking(False)
        self.pushButton_24.setIcon(icon)
        self.pushButton_24.setIconSize(QtCore.QSize(500, 500))
        self.pushButton_24.setObjectName("pushButton_24")
        self.pushButton_25 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_25.setGeometry(QtCore.QRect(420, 310, 51, 51))
        self.pushButton_25.setMouseTracking(False)
        self.pushButton_25.setIcon(icon)
        self.pushButton_25.setIconSize(QtCore.QSize(500, 500))
        self.pushButton_25.setObjectName("pushButton_25")
        self.pushButton_26 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_26.setGeometry(QtCore.QRect(370, 260, 51, 51))
        self.pushButton_26.setMouseTracking(False)
        self.pushButton_26.setIcon(icon)
        self.pushButton_26.setIconSize(QtCore.QSize(500, 500))
        self.pushButton_26.setObjectName("pushButton_26")
        self.pushButton_27 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_27.setGeometry(QtCore.QRect(270, 160, 51, 51))
        self.pushButton_27.setMouseTracking(False)
        self.pushButton_27.setIcon(icon)
        self.pushButton_27.setIconSize(QtCore.QSize(500, 500))
        self.pushButton_27.setObjectName("pushButton_27")
        self.pushButton_28 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_28.setGeometry(QtCore.QRect(320, 210, 51, 51))
        self.pushButton_28.setMouseTracking(False)
        self.pushButton_28.setIcon(icon)
        self.pushButton_28.setIconSize(QtCore.QSize(500, 500))
        self.pushButton_28.setObjectName("pushButton_28")
        self.pushButton_29 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_29.setGeometry(QtCore.QRect(320, 110, 51, 51))
        self.pushButton_29.setMouseTracking(False)
        self.pushButton_29.setIcon(icon)
        self.pushButton_29.setIconSize(QtCore.QSize(500, 500))
        self.pushButton_29.setObjectName("pushButton_29")
        self.pushButton_30 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_30.setGeometry(QtCore.QRect(420, 110, 51, 51))
        self.pushButton_30.setMouseTracking(False)
        self.pushButton_30.setIcon(icon)
        self.pushButton_30.setIconSize(QtCore.QSize(500, 500))
        self.pushButton_30.setObjectName("pushButton_30")
        self.pushButton_31 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_31.setGeometry(QtCore.QRect(370, 160, 51, 51))
        self.pushButton_31.setMouseTracking(False)
        self.pushButton_31.setIcon(icon)
        self.pushButton_31.setIconSize(QtCore.QSize(500, 500))
        self.pushButton_31.setObjectName("pushButton_31")
        self.pushButton_32 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_32.setGeometry(QtCore.QRect(270, 60, 51, 51))
        self.pushButton_32.setMouseTracking(False)
        self.pushButton_32.setIcon(icon)
        self.pushButton_32.setIconSize(QtCore.QSize(500, 500))
        self.pushButton_32.setObjectName("pushButton_32")
        self.pushButton_33 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_33.setGeometry(QtCore.QRect(370, 60, 51, 51))
        self.pushButton_33.setMouseTracking(False)
        self.pushButton_33.setIcon(icon)
        self.pushButton_33.setIconSize(QtCore.QSize(500, 500))
        self.pushButton_33.setObjectName("pushButton_33")
        self.pushButton_34 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_34.setGeometry(QtCore.QRect(70, 160, 51, 51))
        self.pushButton_34.setMouseTracking(False)
        self.pushButton_34.setIcon(icon)
        self.pushButton_34.setIconSize(QtCore.QSize(500, 500))
        self.pushButton_34.setObjectName("pushButton_34")
        self.pushButton_35 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_35.setGeometry(QtCore.QRect(120, 210, 51, 51))
        self.pushButton_35.setMouseTracking(False)
        self.pushButton_35.setIcon(icon)
        self.pushButton_35.setIconSize(QtCore.QSize(500, 500))
        self.pushButton_35.setObjectName("pushButton_35")
        self.pushButton_36 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_36.setGeometry(QtCore.QRect(170, 260, 51, 51))
        self.pushButton_36.setMouseTracking(False)
        self.pushButton_36.setIcon(icon)
        self.pushButton_36.setIconSize(QtCore.QSize(500, 500))
        self.pushButton_36.setObjectName("pushButton_36")
        self.pushButton_37 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_37.setGeometry(QtCore.QRect(220, 310, 51, 51))
        self.pushButton_37.setMouseTracking(False)
        self.pushButton_37.setIcon(icon)
        self.pushButton_37.setIconSize(QtCore.QSize(500, 500))
        self.pushButton_37.setObjectName("pushButton_37")
        self.pushButton_38 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_38.setGeometry(QtCore.QRect(270, 360, 51, 51))
        self.pushButton_38.setMouseTracking(False)
        self.pushButton_38.setIcon(icon)
        self.pushButton_38.setIconSize(QtCore.QSize(500, 500))
        self.pushButton_38.setObjectName("pushButton_38")
        self.pushButton_39 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_39.setGeometry(QtCore.QRect(320, 410, 51, 51))
        self.pushButton_39.setMouseTracking(False)
        self.pushButton_39.setIcon(icon)
        self.pushButton_39.setIconSize(QtCore.QSize(500, 500))
        self.pushButton_39.setObjectName("pushButton_39")
        self.pushButton_40 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_40.setGeometry(QtCore.QRect(70, 260, 51, 51))
        self.pushButton_40.setMouseTracking(False)
        self.pushButton_40.setIcon(icon)
        self.pushButton_40.setIconSize(QtCore.QSize(500, 500))
        self.pushButton_40.setObjectName("pushButton_40")
        self.pushButton_41 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_41.setGeometry(QtCore.QRect(120, 310, 51, 51))
        self.pushButton_41.setMouseTracking(False)
        self.pushButton_41.setIcon(icon)
        self.pushButton_41.setIconSize(QtCore.QSize(500, 500))
        self.pushButton_41.setObjectName("pushButton_41")
        self.pushButton_42 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_42.setGeometry(QtCore.QRect(170, 360, 51, 51))
        self.pushButton_42.setMouseTracking(False)
        self.pushButton_42.setIcon(icon)
        self.pushButton_42.setIconSize(QtCore.QSize(500, 500))
        self.pushButton_42.setObjectName("pushButton_42")
        self.pushButton_43 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_43.setGeometry(QtCore.QRect(220, 410, 51, 51))
        self.pushButton_43.setMouseTracking(False)
        self.pushButton_43.setIcon(icon)
        self.pushButton_43.setIconSize(QtCore.QSize(500, 500))
        self.pushButton_43.setObjectName("pushButton_43")
        self.pushButton_44 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_44.setGeometry(QtCore.QRect(120, 410, 51, 51))
        self.pushButton_44.setMouseTracking(False)
        self.pushButton_44.setIcon(icon)
        self.pushButton_44.setIconSize(QtCore.QSize(500, 500))
        self.pushButton_44.setObjectName("pushButton_44")
        self.pushButton_45 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_45.setGeometry(QtCore.QRect(70, 360, 51, 51))
        self.pushButton_45.setMouseTracking(False)
        self.pushButton_45.setIcon(icon)
        self.pushButton_45.setIconSize(QtCore.QSize(500, 500))
        self.pushButton_45.setObjectName("pushButton_45")
        self.pushButton_46 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_46.setGeometry(QtCore.QRect(120, 60, 51, 51))
        self.pushButton_46.setMouseTracking(False)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("ca51503802ffd1190bd4f1c04e330882.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_46.setIcon(icon1)
        self.pushButton_46.setIconSize(QtCore.QSize(500, 500))
        self.pushButton_46.setObjectName("pushButton_46")
        self.pushButton_47 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_47.setGeometry(QtCore.QRect(220, 60, 51, 51))
        self.pushButton_47.setMouseTracking(False)
        self.pushButton_47.setIcon(icon1)
        self.pushButton_47.setIconSize(QtCore.QSize(500, 500))
        self.pushButton_47.setObjectName("pushButton_47")
        self.pushButton_48 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_48.setGeometry(QtCore.QRect(320, 60, 51, 51))
        self.pushButton_48.setMouseTracking(False)
        self.pushButton_48.setIcon(icon1)
        self.pushButton_48.setIconSize(QtCore.QSize(500, 500))
        self.pushButton_48.setObjectName("pushButton_48")
        self.pushButton_49 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_49.setGeometry(QtCore.QRect(420, 60, 51, 51))
        self.pushButton_49.setMouseTracking(False)
        self.pushButton_49.setIcon(icon1)
        self.pushButton_49.setIconSize(QtCore.QSize(500, 500))
        self.pushButton_49.setObjectName("pushButton_49")
        self.pushButton_50 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_50.setGeometry(QtCore.QRect(370, 110, 51, 51))
        self.pushButton_50.setMouseTracking(False)
        self.pushButton_50.setIcon(icon1)
        self.pushButton_50.setIconSize(QtCore.QSize(500, 500))
        self.pushButton_50.setObjectName("pushButton_50")
        self.pushButton_51 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_51.setGeometry(QtCore.QRect(270, 110, 51, 51))
        self.pushButton_51.setMouseTracking(False)
        self.pushButton_51.setIcon(icon1)
        self.pushButton_51.setIconSize(QtCore.QSize(500, 500))
        self.pushButton_51.setObjectName("pushButton_51")
        self.pushButton_52 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_52.setGeometry(QtCore.QRect(170, 110, 51, 51))
        self.pushButton_52.setMouseTracking(False)
        self.pushButton_52.setIcon(icon1)
        self.pushButton_52.setIconSize(QtCore.QSize(500, 500))
        self.pushButton_52.setObjectName("pushButton_52")
        self.pushButton_53 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_53.setGeometry(QtCore.QRect(70, 110, 51, 51))
        self.pushButton_53.setMouseTracking(False)
        self.pushButton_53.setIcon(icon1)
        self.pushButton_53.setIconSize(QtCore.QSize(500, 500))
        self.pushButton_53.setObjectName("pushButton_53")
        self.pushButton_54 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_54.setGeometry(QtCore.QRect(120, 160, 51, 51))
        self.pushButton_54.setMouseTracking(False)
        self.pushButton_54.setIcon(icon1)
        self.pushButton_54.setIconSize(QtCore.QSize(500, 500))
        self.pushButton_54.setObjectName("pushButton_54")
        self.pushButton_55 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_55.setGeometry(QtCore.QRect(220, 160, 51, 51))
        self.pushButton_55.setMouseTracking(False)
        self.pushButton_55.setIcon(icon1)
        self.pushButton_55.setIconSize(QtCore.QSize(500, 500))
        self.pushButton_55.setObjectName("pushButton_55")
        self.pushButton_56 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_56.setGeometry(QtCore.QRect(320, 160, 51, 51))
        self.pushButton_56.setMouseTracking(False)
        self.pushButton_56.setIcon(icon1)
        self.pushButton_56.setIconSize(QtCore.QSize(500, 500))
        self.pushButton_56.setObjectName("pushButton_56")
        self.pushButton_57 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_57.setGeometry(QtCore.QRect(420, 160, 51, 51))
        self.pushButton_57.setMouseTracking(False)
        self.pushButton_57.setIcon(icon1)
        self.pushButton_57.setIconSize(QtCore.QSize(500, 500))
        self.pushButton_57.setObjectName("pushButton_57")
        self.pushButton_58 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_58.setGeometry(QtCore.QRect(420, 260, 51, 51))
        self.pushButton_58.setMouseTracking(False)
        self.pushButton_58.setIcon(icon1)
        self.pushButton_58.setIconSize(QtCore.QSize(500, 500))
        self.pushButton_58.setObjectName("pushButton_58")
        self.pushButton_59 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_59.setGeometry(QtCore.QRect(420, 360, 51, 51))
        self.pushButton_59.setMouseTracking(False)
        self.pushButton_59.setIcon(icon1)
        self.pushButton_59.setIconSize(QtCore.QSize(500, 500))
        self.pushButton_59.setObjectName("pushButton_59")
        self.pushButton_60 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_60.setGeometry(QtCore.QRect(370, 410, 51, 51))
        self.pushButton_60.setMouseTracking(False)
        self.pushButton_60.setIcon(icon1)
        self.pushButton_60.setIconSize(QtCore.QSize(500, 500))
        self.pushButton_60.setObjectName("pushButton_60")
        self.pushButton_61 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_61.setGeometry(QtCore.QRect(270, 410, 51, 51))
        self.pushButton_61.setMouseTracking(False)
        self.pushButton_61.setIcon(icon1)
        self.pushButton_61.setIconSize(QtCore.QSize(500, 500))
        self.pushButton_61.setObjectName("pushButton_61")
        self.pushButton_62 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_62.setGeometry(QtCore.QRect(170, 410, 51, 51))
        self.pushButton_62.setMouseTracking(False)
        self.pushButton_62.setIcon(icon1)
        self.pushButton_62.setIconSize(QtCore.QSize(500, 500))
        self.pushButton_62.setObjectName("pushButton_62")
        self.pushButton_63 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_63.setGeometry(QtCore.QRect(70, 410, 51, 51))
        self.pushButton_63.setMouseTracking(False)
        self.pushButton_63.setIcon(icon1)
        self.pushButton_63.setIconSize(QtCore.QSize(500, 500))
        self.pushButton_63.setObjectName("pushButton_63")
        self.pushButton_64 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_64.setGeometry(QtCore.QRect(120, 360, 51, 51))
        self.pushButton_64.setMouseTracking(False)
        self.pushButton_64.setIcon(icon1)
        self.pushButton_64.setIconSize(QtCore.QSize(500, 500))
        self.pushButton_64.setObjectName("pushButton_64")
        self.pushButton_65 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_65.setGeometry(QtCore.QRect(70, 310, 51, 51))
        self.pushButton_65.setMouseTracking(False)
        self.pushButton_65.setIcon(icon1)
        self.pushButton_65.setIconSize(QtCore.QSize(500, 500))
        self.pushButton_65.setObjectName("pushButton_65")
        self.pushButton_66 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_66.setGeometry(QtCore.QRect(70, 210, 51, 51))
        self.pushButton_66.setMouseTracking(False)
        self.pushButton_66.setIcon(icon1)
        self.pushButton_66.setIconSize(QtCore.QSize(500, 500))
        self.pushButton_66.setObjectName("pushButton_66")
        self.pushButton_67 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_67.setGeometry(QtCore.QRect(170, 310, 51, 51))
        self.pushButton_67.setMouseTracking(False)
        self.pushButton_67.setIcon(icon1)
        self.pushButton_67.setIconSize(QtCore.QSize(500, 500))
        self.pushButton_67.setObjectName("pushButton_67")
        self.pushButton_68 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_68.setGeometry(QtCore.QRect(220, 360, 51, 51))
        self.pushButton_68.setMouseTracking(False)
        self.pushButton_68.setIcon(icon1)
        self.pushButton_68.setIconSize(QtCore.QSize(500, 500))
        self.pushButton_68.setObjectName("pushButton_68")
        self.pushButton_69 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_69.setGeometry(QtCore.QRect(320, 360, 51, 51))
        self.pushButton_69.setMouseTracking(False)
        self.pushButton_69.setIcon(icon1)
        self.pushButton_69.setIconSize(QtCore.QSize(500, 500))
        self.pushButton_69.setObjectName("pushButton_69")
        self.pushButton_70 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_70.setGeometry(QtCore.QRect(370, 310, 51, 51))
        self.pushButton_70.setMouseTracking(False)
        self.pushButton_70.setIcon(icon1)
        self.pushButton_70.setIconSize(QtCore.QSize(500, 500))
        self.pushButton_70.setObjectName("pushButton_70")
        self.pushButton_71 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_71.setGeometry(QtCore.QRect(320, 260, 51, 51))
        self.pushButton_71.setMouseTracking(False)
        self.pushButton_71.setIcon(icon1)
        self.pushButton_71.setIconSize(QtCore.QSize(500, 500))
        self.pushButton_71.setObjectName("pushButton_71")
        self.pushButton_72 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_72.setGeometry(QtCore.QRect(370, 210, 51, 51))
        self.pushButton_72.setMouseTracking(False)
        self.pushButton_72.setIcon(icon1)
        self.pushButton_72.setIconSize(QtCore.QSize(500, 500))
        self.pushButton_72.setObjectName("pushButton_72")
        self.pushButton_73 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_73.setGeometry(QtCore.QRect(270, 210, 51, 51))
        self.pushButton_73.setMouseTracking(False)
        self.pushButton_73.setIcon(icon1)
        self.pushButton_73.setIconSize(QtCore.QSize(500, 500))
        self.pushButton_73.setObjectName("pushButton_73")
        self.pushButton_74 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_74.setGeometry(QtCore.QRect(270, 310, 51, 51))
        self.pushButton_74.setMouseTracking(False)
        self.pushButton_74.setIcon(icon1)
        self.pushButton_74.setIconSize(QtCore.QSize(500, 500))
        self.pushButton_74.setObjectName("pushButton_74")
        self.pushButton_75 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_75.setGeometry(QtCore.QRect(220, 260, 51, 51))
        self.pushButton_75.setMouseTracking(False)
        self.pushButton_75.setIcon(icon1)
        self.pushButton_75.setIconSize(QtCore.QSize(500, 500))
        self.pushButton_75.setObjectName("pushButton_75")
        self.pushButton_76 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_76.setGeometry(QtCore.QRect(170, 210, 51, 51))
        self.pushButton_76.setMouseTracking(False)
        self.pushButton_76.setIcon(icon1)
        self.pushButton_76.setIconSize(QtCore.QSize(500, 500))
        self.pushButton_76.setObjectName("pushButton_76")
        self.pushButton_77 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_77.setGeometry(QtCore.QRect(120, 260, 51, 51))
        self.pushButton_77.setMouseTracking(False)
        self.pushButton_77.setIcon(icon1)
        self.pushButton_77.setIconSize(QtCore.QSize(500, 500))
        self.pushButton_77.setObjectName("pushButton_77")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(80, 10, 401, 44))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(26)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.label_3 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(26)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_3.setFont(font)
        self.label_3.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout.addWidget(self.label_3)
        self.label_4 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(26)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_4.setFont(font)
        self.label_4.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout.addWidget(self.label_4)
        self.label_5 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(26)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_5.setFont(font)
        self.label_5.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout.addWidget(self.label_5)
        self.label_6 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(26)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_6.setFont(font)
        self.label_6.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout.addWidget(self.label_6)
        self.label_7 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(26)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_7.setFont(font)
        self.label_7.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout.addWidget(self.label_7)
        self.label_8 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(26)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_8.setFont(font)
        self.label_8.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout.addWidget(self.label_8)
        self.label_9 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(26)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_9.setFont(font)
        self.label_9.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout.addWidget(self.label_9)
        self.layoutWidget1 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget1.setGeometry(QtCore.QRect(40, 60, 21, 401))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_2 = QtWidgets.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(26)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_2.setFont(font)
        self.label_2.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.label_10 = QtWidgets.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(26)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_10.setFont(font)
        self.label_10.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_10.setObjectName("label_10")
        self.verticalLayout.addWidget(self.label_10)
        self.label_11 = QtWidgets.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(26)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_11.setFont(font)
        self.label_11.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_11.setObjectName("label_11")
        self.verticalLayout.addWidget(self.label_11)
        self.label_14 = QtWidgets.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(26)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_14.setFont(font)
        self.label_14.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_14.setObjectName("label_14")
        self.verticalLayout.addWidget(self.label_14)
        self.label_16 = QtWidgets.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(26)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_16.setFont(font)
        self.label_16.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_16.setObjectName("label_16")
        self.verticalLayout.addWidget(self.label_16)
        self.label_15 = QtWidgets.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(26)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_15.setFont(font)
        self.label_15.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_15.setObjectName("label_15")
        self.verticalLayout.addWidget(self.label_15)
        self.label_13 = QtWidgets.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(26)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_13.setFont(font)
        self.label_13.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_13.setObjectName("label_13")
        self.verticalLayout.addWidget(self.label_13)
        self.label_12 = QtWidgets.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(26)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_12.setFont(font)
        self.label_12.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_12.setObjectName("label_12")
        self.verticalLayout.addWidget(self.label_12)
        self.pushButton1 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton1.setGeometry(QtCore.QRect(570, 20, 61, 71))
        self.pushButton1.setText("1")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("2.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton1.setIcon(icon2)
        self.pushButton1.setIconSize(QtCore.QSize(700, 400))
        self.pushButton1.setObjectName("pushButton_2")
        self.pushButton2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton2.setGeometry(QtCore.QRect(570, 100, 61, 61))
        self.pushButton2.setText("2")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("3.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton2.setIcon(icon3)
        self.pushButton2.setIconSize(QtCore.QSize(70, 500))
        self.pushButton2.setObjectName("pushButton_3")
        self.pushButton3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton3.setGeometry(QtCore.QRect(570, 170, 61, 61))
        self.pushButton3.setText("3")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("4.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton3.setIcon(icon4)
        self.pushButton3.setIconSize(QtCore.QSize(70, 500))
        self.pushButton3.setObjectName("pushButton")
        self.pushButton4 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton4.setGeometry(QtCore.QRect(570, 240, 61, 61))
        self.pushButton4.setText("4")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("5.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton4.setIcon(icon5)
        self.pushButton4.setIconSize(QtCore.QSize(70, 500))
        self.pushButton4.setObjectName("pushButton_4")
        self.lable_fin = QtWidgets.QLabel(self.centralwidget)
        self.lable_fin.setGeometry(QtCore.QRect(550, 390, 121, 16))
        self.lable_fin.setText("")
        self.lable_fin.setObjectName("lable_fin")
        MainWindo.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindo)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 728, 21))
        self.menubar.setObjectName("menubar")
        MainWindo.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindo)
        self.statusbar.setObjectName("statusbar")
        MainWindo.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindo)
        QtCore.QMetaObject.connectSlotsByName(MainWindo)
        
        
        self.pushButton1.clicked.connect(lambda: self.Func1(str(self.pushButton1.text())))
        self.pushButton2.clicked.connect(lambda: self.Func1(str(self.pushButton2.text())))
        self.pushButton3.clicked.connect(lambda: self.Func1(str(self.pushButton3.text())))
        self.pushButton4.clicked.connect(lambda: self.Func1(str(self.pushButton4.text())))
        
        self.pushButton_14.clicked.connect(lambda: self.Func(str(self.pushButton_14.text())))
        self.pushButton_15.clicked.connect(lambda: self.Func(str(self.pushButton_15.text())))
        self.pushButton_16.clicked.connect(lambda: self.Func(str(self.pushButton_16.text())))
        self.pushButton_17.clicked.connect(lambda: self.Func(str(self.pushButton_17.text())))
        self.pushButton_18.clicked.connect(lambda: self.Func(str(self.pushButton_18.text())))
        self.pushButton_19.clicked.connect(lambda: self.Func(str(self.pushButton_19.text())))
        self.pushButton_20.clicked.connect(lambda: self.Func(str(self.pushButton_20.text())))
        self.pushButton_21.clicked.connect(lambda: self.Func(str(self.pushButton_21.text())))
        self.pushButton_22.clicked.connect(lambda: self.Func(str(self.pushButton_22.text())))
        self.pushButton_23.clicked.connect(lambda: self.Func(str(self.pushButton_23.text())))
        self.pushButton_24.clicked.connect(lambda: self.Func(str(self.pushButton_24.text())))
        self.pushButton_25.clicked.connect(lambda: self.Func(str(self.pushButton_25.text())))
        self.pushButton_26.clicked.connect(lambda: self.Func(str(self.pushButton_26.text())))
        self.pushButton_27.clicked.connect(lambda: self.Func(str(self.pushButton_27.text())))
        self.pushButton_28.clicked.connect(lambda: self.Func(str(self.pushButton_28.text())))
        self.pushButton_29.clicked.connect(lambda: self.Func(str(self.pushButton_29.text())))
        self.pushButton_30.clicked.connect(lambda: self.Func(str(self.pushButton_30.text())))
        self.pushButton_31.clicked.connect(lambda: self.Func(str(self.pushButton_31.text())))
        self.pushButton_32.clicked.connect(lambda: self.Func(str(self.pushButton_32.text())))
        self.pushButton_33.clicked.connect(lambda: self.Func(str(self.pushButton_33.text())))
        self.pushButton_34.clicked.connect(lambda: self.Func(str(self.pushButton_34.text())))
        self.pushButton_35.clicked.connect(lambda: self.Func(str(self.pushButton_35.text())))
        self.pushButton_36.clicked.connect(lambda: self.Func(str(self.pushButton_36.text())))
        self.pushButton_37.clicked.connect(lambda: self.Func(str(self.pushButton_37.text())))
        self.pushButton_38.clicked.connect(lambda: self.Func(str(self.pushButton_38.text())))
        self.pushButton_39.clicked.connect(lambda: self.Func(str(self.pushButton_39.text())))
        self.pushButton_40.clicked.connect(lambda: self.Func(str(self.pushButton_40.text())))
        self.pushButton_41.clicked.connect(lambda: self.Func(str(self.pushButton_41.text())))
        self.pushButton_42.clicked.connect(lambda: self.Func(str(self.pushButton_42.text())))
        self.pushButton_43.clicked.connect(lambda: self.Func(str(self.pushButton_43.text())))
        self.pushButton_44.clicked.connect(lambda: self.Func(str(self.pushButton_44.text())))
        self.pushButton_45.clicked.connect(lambda: self.Func(str(self.pushButton_45.text())))
        self.pushButton_46.clicked.connect(lambda: self.Func(str(self.pushButton_46.text())))
        self.pushButton_47.clicked.connect(lambda: self.Func(str(self.pushButton_47.text())))
        self.pushButton_48.clicked.connect(lambda: self.Func(str(self.pushButton_48.text())))
        self.pushButton_49.clicked.connect(lambda: self.Func(str(self.pushButton_49.text())))
        self.pushButton_50.clicked.connect(lambda: self.Func(str(self.pushButton_50.text())))
        self.pushButton_51.clicked.connect(lambda: self.Func(str(self.pushButton_51.text())))
        self.pushButton_52.clicked.connect(lambda: self.Func(str(self.pushButton_52.text())))
        self.pushButton_53.clicked.connect(lambda: self.Func(str(self.pushButton_53.text())))
        self.pushButton_54.clicked.connect(lambda: self.Func(str(self.pushButton_54.text())))
        self.pushButton_55.clicked.connect(lambda: self.Func(str(self.pushButton_55.text())))
        self.pushButton_56.clicked.connect(lambda: self.Func(str(self.pushButton_56.text())))
        self.pushButton_57.clicked.connect(lambda: self.Func(str(self.pushButton_57.text())))
        self.pushButton_58.clicked.connect(lambda: self.Func(str(self.pushButton_58.text())))
        self.pushButton_59.clicked.connect(lambda: self.Func(str(self.pushButton_59.text())))
        self.pushButton_60.clicked.connect(lambda: self.Func(str(self.pushButton_60.text())))
        self.pushButton_61.clicked.connect(lambda: self.Func(str(self.pushButton_61.text())))
        self.pushButton_62.clicked.connect(lambda: self.Func(str(self.pushButton_62.text())))
        self.pushButton_63.clicked.connect(lambda: self.Func(str(self.pushButton_63.text())))
        self.pushButton_64.clicked.connect(lambda: self.Func(str(self.pushButton_64.text())))
        self.pushButton_65.clicked.connect(lambda: self.Func(str(self.pushButton_65.text())))
        self.pushButton_66.clicked.connect(lambda: self.Func(str(self.pushButton_66.text())))
        self.pushButton_67.clicked.connect(lambda: self.Func(str(self.pushButton_67.text())))
        self.pushButton_68.clicked.connect(lambda: self.Func(str(self.pushButton_68.text())))
        self.pushButton_69.clicked.connect(lambda: self.Func(str(self.pushButton_69.text())))
        self.pushButton_70.clicked.connect(lambda: self.Func(str(self.pushButton_70.text())))
        self.pushButton_71.clicked.connect(lambda: self.Func(str(self.pushButton_71.text())))
        self.pushButton_72.clicked.connect(lambda: self.Func(str(self.pushButton_72.text())))
        self.pushButton_73.clicked.connect(lambda: self.Func(str(self.pushButton_73.text())))
        self.pushButton_74.clicked.connect(lambda: self.Func(str(self.pushButton_74.text())))
        self.pushButton_75.clicked.connect(lambda: self.Func(str(self.pushButton_75.text())))
        self.pushButton_76.clicked.connect(lambda: self.Func(str(self.pushButton_76.text())))
        self.pushButton_77.clicked.connect(lambda: self.Func(str(self.pushButton_77.text())))


    def retranslateUi(self, MainWindo):
        _translate = QtCore.QCoreApplication.translate
        MainWindo.setWindowTitle(_translate("MainWindo", "MainWindow"))
        self.pushButton_14.setText(_translate("MainWindo", "11"))
        self.pushButton_15.setText(_translate("MainWindo", "22"))
        self.pushButton_16.setText(_translate("MainWindo", "33"))
        self.pushButton_17.setText(_translate("MainWindo", "44"))
        self.pushButton_18.setText(_translate("MainWindo", "55"))
        self.pushButton_19.setText(_translate("MainWindo", "66"))
        self.pushButton_20.setText(_translate("MainWindo", "77"))
        self.pushButton_21.setText(_translate("MainWindo", "88"))
        self.pushButton_22.setText(_translate("MainWindo", "13"))
        self.pushButton_23.setText(_translate("MainWindo", "48"))
        self.pushButton_24.setText(_translate("MainWindo", "24"))
        self.pushButton_25.setText(_translate("MainWindo", "68"))
        self.pushButton_26.setText(_translate("MainWindo", "57"))
        self.pushButton_27.setText(_translate("MainWindo", "35"))
        self.pushButton_28.setText(_translate("MainWindo", "46"))
        self.pushButton_29.setText(_translate("MainWindo", "26"))
        self.pushButton_30.setText(_translate("MainWindo", "28"))
        self.pushButton_31.setText(_translate("MainWindo", "37"))
        self.pushButton_32.setText(_translate("MainWindo", "15"))
        self.pushButton_33.setText(_translate("MainWindo", "17"))
        self.pushButton_34.setText(_translate("MainWindo", "31"))
        self.pushButton_35.setText(_translate("MainWindo", "42"))
        self.pushButton_36.setText(_translate("MainWindo", "53"))
        self.pushButton_37.setText(_translate("MainWindo", "64"))
        self.pushButton_38.setText(_translate("MainWindo", "75"))
        self.pushButton_39.setText(_translate("MainWindo", "86"))
        self.pushButton_40.setText(_translate("MainWindo", "51"))
        self.pushButton_41.setText(_translate("MainWindo", "62"))
        self.pushButton_42.setText(_translate("MainWindo", "73"))
        self.pushButton_43.setText(_translate("MainWindo", "84"))
        self.pushButton_44.setText(_translate("MainWindo", "82"))
        self.pushButton_45.setText(_translate("MainWindo", "71"))
        self.pushButton_46.setText(_translate("MainWindo", "12"))
        self.pushButton_47.setText(_translate("MainWindo", "14"))
        self.pushButton_48.setText(_translate("MainWindo", "16"))
        self.pushButton_49.setText(_translate("MainWindo", "18"))
        self.pushButton_50.setText(_translate("MainWindo", "27"))
        self.pushButton_51.setText(_translate("MainWindo", "25"))
        self.pushButton_52.setText(_translate("MainWindo", "23"))
        self.pushButton_53.setText(_translate("MainWindo", "21"))
        self.pushButton_54.setText(_translate("MainWindo", "32"))
        self.pushButton_55.setText(_translate("MainWindo", "34"))
        self.pushButton_56.setText(_translate("MainWindo", "36"))
        self.pushButton_57.setText(_translate("MainWindo", "38"))
        self.pushButton_58.setText(_translate("MainWindo", "58"))
        self.pushButton_59.setText(_translate("MainWindo", "78"))
        self.pushButton_60.setText(_translate("MainWindo", "87"))
        self.pushButton_61.setText(_translate("MainWindo", "85"))
        self.pushButton_62.setText(_translate("MainWindo", "83"))
        self.pushButton_63.setText(_translate("MainWindo", "81"))
        self.pushButton_64.setText(_translate("MainWindo", "72"))
        self.pushButton_65.setText(_translate("MainWindo", "61"))
        self.pushButton_66.setText(_translate("MainWindo", "41"))
        self.pushButton_67.setText(_translate("MainWindo", "63"))
        self.pushButton_68.setText(_translate("MainWindo", "74"))
        self.pushButton_69.setText(_translate("MainWindo", "76"))
        self.pushButton_70.setText(_translate("MainWindo", "67"))
        self.pushButton_71.setText(_translate("MainWindo", "56"))
        self.pushButton_72.setText(_translate("MainWindo", "47"))
        self.pushButton_73.setText(_translate("MainWindo", "45"))
        self.pushButton_74.setText(_translate("MainWindo", "65"))
        self.pushButton_75.setText(_translate("MainWindo", "54"))
        self.pushButton_76.setText(_translate("MainWindo", "43"))
        self.pushButton_77.setText(_translate("MainWindo", "52"))
        self.label.setText(_translate("MainWindo", "1"))
        self.label_3.setText(_translate("MainWindo", "2"))
        self.label_4.setText(_translate("MainWindo", "3"))
        self.label_5.setText(_translate("MainWindo", "4"))
        self.label_6.setText(_translate("MainWindo", "5"))
        self.label_7.setText(_translate("MainWindo", "6"))
        self.label_8.setText(_translate("MainWindo", "7"))
        self.label_9.setText(_translate("MainWindo", "8"))
        self.label_2.setText(_translate("MainWindo", "1"))
        self.label_10.setText(_translate("MainWindo", "2"))
        self.label_11.setText(_translate("MainWindo", "3"))
        self.label_14.setText(_translate("MainWindo", "4"))
        self.label_16.setText(_translate("MainWindo", "5"))
        self.label_15.setText(_translate("MainWindo", "6"))
        self.label_13.setText(_translate("MainWindo", "7"))
        self.label_12.setText(_translate("MainWindo", "8"))

    def f1(self, x1, x2, y1, y2): # Конь
        print("Конь")
        if abs(x1 - x2) * abs(y1 - y2) == 2: 
            self.lable_fin.setText("Бьют") 
        else: 
            self.lable_fin.setText("Не бьют") 

    def f4(self, x1, x2, y1, y2): # Ладья 
        if x1 == x2 or y1 == y2: 
            self.lable_fin.setText("Бьют") 
        else: 
            self.lable_fin.setText("Не бьют")  

    def f2(self, x1, x2, y1, y2): # Слон
        if abs(x1 - x2) == abs(y1 - y2): 
            self.lable_fin.setText("Бьют")  
        else: 
            self.lable_fin.setText("Не бьют") 

    def f3(self, x1, x2, y1, y2): # Ферзь
        if abs(x1 - x2) == abs(y1 - y2) or (x1 == x2) or (y1 == y2): 
            self.lable_fin.setText("Бьют")  
        else: 
            self.lable_fin.setText("Не бьют") 


    def Func1(self,a):# При нажатии на фигуру её название появляется в лейбле 
        global j 
        j = int(a)
        if j == 1:
            self.lable_fin.setText("Конь")
        if j == 2:
            self.lable_fin.setText("Слон")
        if j == 3:
            self.lable_fin.setText("Ферзь")
        if j == 4:
            self.lable_fin.setText("Ладья")
        
    def Func(self, a):# При нажатии на доску, сохраняет координаты 
        global k
        global x1
        global x2
        global y1
        global y2 
        global j# Эта переменная отвечет за фигуру
        if k == 1:# Если это первое нажатие 
            x2 = int(a[0])
            y2 = int(a[1])
            k = k + 1
        else:# Если это второе нажатие
            x1 = int(a[0])
            y1 = int(a[1])
            k = k + 1
        if k == 2:# Если произошло 2 нажатия
            if j == 1:
                self.f1(x1,x2,y1,y2)
            elif j == 2:
                self.f2(x1,x2,y1,y2)
            elif j == 3:
                self.f3(x1,x2,y1,y2)
            elif j == 4:
                self.f4(x1,x2,y1,y2)
            k = 0          

import sys

if __name__ == "__main__":
    app = QtWidgets.QApplication(sys.argv)
    MainWindo = QtWidgets.QMainWindow()
    ui = Ui_MainWindo()
    ui.setupUi(MainWindo)
    MainWindo.show()
    sys.exit(app.exec_())